// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS4AeNPx2M_5lQv6WJ6RP85rYSe4Z-J2g',
    appId: '1:853054702494:web:44143d42ab2bb207a30c8f',
    messagingSenderId: '853054702494',
    projectId: 'docbooking-9ec13',
    authDomain: 'docbooking-9ec13.firebaseapp.com',
    databaseURL: 'https://docbooking-9ec13-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'docbooking-9ec13.appspot.com',
    measurementId: 'G-NFRY5PWFLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA2yNxEEZ2QKHWnEuUsxOiDH9Yv74ZHko',
    appId: '1:853054702494:android:f62bb1ccd3917160a30c8f',
    messagingSenderId: '853054702494',
    projectId: 'docbooking-9ec13',
    databaseURL: 'https://docbooking-9ec13-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'docbooking-9ec13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG7wTqlePvOwOGZ5IhL9YFC2krgYsIoSw',
    appId: '1:853054702494:ios:4900dc40f79da0a2a30c8f',
    messagingSenderId: '853054702494',
    projectId: 'docbooking-9ec13',
    databaseURL: 'https://docbooking-9ec13-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'docbooking-9ec13.appspot.com',
    androidClientId: '853054702494-mu3t22rvpomif6mosvosjhgv12r5q1t5.apps.googleusercontent.com',
    iosClientId: '853054702494-f5t4ei19bcjvbr9llc3jkccrrki1q5kk.apps.googleusercontent.com',
    iosBundleId: 'com.quadvare.clinic.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG7wTqlePvOwOGZ5IhL9YFC2krgYsIoSw',
    appId: '1:853054702494:ios:a2b98d598a648e97a30c8f',
    messagingSenderId: '853054702494',
    projectId: 'docbooking-9ec13',
    databaseURL: 'https://docbooking-9ec13-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'docbooking-9ec13.appspot.com',
    androidClientId: '853054702494-mu3t22rvpomif6mosvosjhgv12r5q1t5.apps.googleusercontent.com',
    iosClientId: '853054702494-o5jqmnkvtm8i8vpjdsbthgg0s7nq9auq.apps.googleusercontent.com',
    iosBundleId: 'com.example.medizaAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtIyIxmqdaXN9jLT-P3Zo60iJVifPpXEE',
    appId: '1:853054702494:web:d9bdc5c8e7592cd7a30c8f',
    messagingSenderId: '853054702494',
    projectId: 'docbooking-9ec13',
    authDomain: 'docbooking-9ec13.firebaseapp.com',
    databaseURL: 'https://docbooking-9ec13-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'docbooking-9ec13.appspot.com',
    measurementId: 'G-HT1DPB44FW',
  );

}